[2023-07-30 22:05:29,381] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_smtp_email_automatico.dag_envio scheduled__2023-03-31T00:00:00+00:00 [queued]>
[2023-07-30 22:05:29,405] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_smtp_email_automatico.dag_envio scheduled__2023-03-31T00:00:00+00:00 [queued]>
[2023-07-30 22:05:29,405] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-30 22:05:29,405] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-07-30 22:05:29,405] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-30 22:05:29,470] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): dag_envio> on 2023-03-31 00:00:00+00:00
[2023-07-30 22:05:29,481] {standard_task_runner.py:52} INFO - Started process 1289 to run task
[2023-07-30 22:05:29,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_smtp_email_automatico', 'dag_envio', 'scheduled__2023-03-31T00:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/dag_smtp_email.py', '--cfg-path', '/tmp/tmpzt4k8p4z', '--error-file', '/tmp/tmpczuf6wgf']
[2023-07-30 22:05:29,508] {standard_task_runner.py:80} INFO - Job 207: Subtask dag_envio
[2023-07-30 22:05:29,638] {task_command.py:371} INFO - Running <TaskInstance: dag_smtp_email_automatico.dag_envio scheduled__2023-03-31T00:00:00+00:00 [running]> on host b0e2d990d7ae
[2023-07-30 22:05:29,795] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=dag_smtp_email_automatico
AIRFLOW_CTX_TASK_ID=dag_envio
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-31T00:00:00+00:00
[2023-07-30 22:05:32,067] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials bi29-20020a056808189d00b003a5b027ccb2sm3605632oib.38 - gsmtp')
[2023-07-30 22:05:32,068] {logging_mixin.py:115} INFO - Failure
[2023-07-30 22:05:32,068] {python.py:173} INFO - Done. Returned value was: None
[2023-07-30 22:05:32,091] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=dag_smtp_email_automatico, task_id=dag_envio, execution_date=20230331T000000, start_date=20230730T220529, end_date=20230730T220532
[2023-07-30 22:05:32,139] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-30 22:05:32,185] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
