[2023-08-01 23:12:57,965] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.transform manual__2023-08-01T23:12:54.059731+00:00 [queued]>
[2023-08-01 23:12:57,985] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.transform manual__2023-08-01T23:12:54.059731+00:00 [queued]>
[2023-08-01 23:12:57,986] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:12:57,986] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-08-01 23:12:57,986] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:12:58,016] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): transform> on 2023-08-01 23:12:54.059731+00:00
[2023-08-01 23:12:58,029] {standard_task_runner.py:52} INFO - Started process 1452 to run task
[2023-08-01 23:12:58,034] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_api_marvel_2', 'transform', 'manual__2023-08-01T23:12:54.059731+00:00', '--job-id', '1267', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_multiple_tasks_no_failure.py', '--cfg-path', '/tmp/tmpgjcxete1', '--error-file', '/tmp/tmp23_8_gwx']
[2023-08-01 23:12:58,037] {standard_task_runner.py:80} INFO - Job 1267: Subtask transform
[2023-08-01 23:12:58,159] {task_command.py:371} INFO - Running <TaskInstance: etl_api_marvel_2.transform manual__2023-08-01T23:12:54.059731+00:00 [running]> on host 24cbf2f01ed0
[2023-08-01 23:12:58,304] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=etl_api_marvel_2
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T23:12:54.059731+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T23:12:54.059731+00:00
[2023-08-01 23:12:58,364] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 23:12:58,380] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_api_marvel_2, task_id=transform, execution_date=20230801T231254, start_date=20230801T231257, end_date=20230801T231258
[2023-08-01 23:12:58,409] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 23:12:58,437] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-08-01 23:13:00,998] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
