[2023-07-16 01:16:50,455] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: probando_conexion.primera_tarea manual__2023-07-16T01:14:40.427052+00:00 [queued]>
[2023-07-16 01:16:50,494] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: probando_conexion.primera_tarea manual__2023-07-16T01:14:40.427052+00:00 [queued]>
[2023-07-16 01:16:50,494] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 01:16:50,495] {taskinstance.py:1377} INFO - Starting attempt 2 of 11
[2023-07-16 01:16:50,495] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-16 01:16:50,563] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): primera_tarea> on 2023-07-16 01:14:40.427052+00:00
[2023-07-16 01:16:50,575] {standard_task_runner.py:52} INFO - Started process 8259 to run task
[2023-07-16 01:16:50,586] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'probando_conexion', 'primera_tarea', 'manual__2023-07-16T01:14:40.427052+00:00', '--job-id', '860', '--raw', '--subdir', 'DAGS_FOLDER/variables_y_secrets.py', '--cfg-path', '/tmp/tmp23o49zhg', '--error-file', '/tmp/tmp0p01vmsv']
[2023-07-16 01:16:50,588] {standard_task_runner.py:80} INFO - Job 860: Subtask primera_tarea
[2023-07-16 01:16:50,924] {task_command.py:371} INFO - Running <TaskInstance: probando_conexion.primera_tarea manual__2023-07-16T01:14:40.427052+00:00 [running]> on host 7a1b6d75866e
[2023-07-16 01:16:51,597] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=probando_conexion
AIRFLOW_CTX_TASK_ID=primera_tarea
AIRFLOW_CTX_EXECUTION_DATE=2023-07-16T01:14:40.427052+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-16T01:14:40.427052+00:00
[2023-07-16 01:16:52,673] {logging_mixin.py:115} INFO - ya existe el archivo
[2023-07-16 01:16:52,741] {logging_mixin.py:115} INFO - Index(['id_character', 'nombre', 'descripcion', 'cantidad_de_comics',
       'cantidad_de_series', 'cantidad_de_historias', 'fecha_modificacion'],
      dtype='object')
[2023-07-16 01:16:52,742] {logging_mixin.py:115} INFO - (20, 7)
[2023-07-16 01:16:52,742] {logging_mixin.py:115} INFO - Ya existe el csv:  /opt/***/data/compania1/
[2023-07-16 01:17:07,184] {python.py:173} INFO - Done. Returned value was: None
[2023-07-16 01:17:07,248] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=probando_conexion, task_id=primera_tarea, execution_date=20230716T011440, start_date=20230716T011650, end_date=20230716T011707
[2023-07-16 01:17:07,324] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-16 01:17:07,413] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
