[2023-08-01 23:28:29,193] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.extract manual__2023-08-01T23:28:27.260041+00:00 [queued]>
[2023-08-01 23:28:29,223] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.extract manual__2023-08-01T23:28:27.260041+00:00 [queued]>
[2023-08-01 23:28:29,223] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:28:29,223] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-08-01 23:28:29,223] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:28:29,260] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2023-08-01 23:28:27.260041+00:00
[2023-08-01 23:28:29,271] {standard_task_runner.py:52} INFO - Started process 2140 to run task
[2023-08-01 23:28:29,279] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_api_marvel_2', 'extract', 'manual__2023-08-01T23:28:27.260041+00:00', '--job-id', '1277', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_failure.py', '--cfg-path', '/tmp/tmpr5iwbk0b', '--error-file', '/tmp/tmppu69zpjk']
[2023-08-01 23:28:29,281] {standard_task_runner.py:80} INFO - Job 1277: Subtask extract
[2023-08-01 23:28:29,427] {task_command.py:371} INFO - Running <TaskInstance: etl_api_marvel_2.extract manual__2023-08-01T23:28:27.260041+00:00 [running]> on host 24cbf2f01ed0
[2023-08-01 23:28:29,581] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=etl_api_marvel_2
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T23:28:27.260041+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T23:28:27.260041+00:00
[2023-08-01 23:28:30,593] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 23:28:30,617] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_api_marvel_2, task_id=extract, execution_date=20230801T232827, start_date=20230801T232829, end_date=20230801T232830
[2023-08-01 23:28:30,659] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 23:28:30,705] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-08-01 23:28:30,717] {logging_mixin.py:115} INFO - None
[2023-08-01 23:28:33,745] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
