[2023-08-02 01:02:19,389] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.extract manual__2023-08-02T01:02:16.701192+00:00 [queued]>
[2023-08-02 01:02:19,423] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.extract manual__2023-08-02T01:02:16.701192+00:00 [queued]>
[2023-08-02 01:02:19,424] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 01:02:19,424] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-08-02 01:02:19,424] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 01:02:19,474] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2023-08-02 01:02:16.701192+00:00
[2023-08-02 01:02:19,484] {standard_task_runner.py:52} INFO - Started process 6262 to run task
[2023-08-02 01:02:19,490] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_api_marvel_2', 'extract', 'manual__2023-08-02T01:02:16.701192+00:00', '--job-id', '1307', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_failure.py', '--cfg-path', '/tmp/tmpkqh0yj1q', '--error-file', '/tmp/tmp58ny0cp8']
[2023-08-02 01:02:19,503] {standard_task_runner.py:80} INFO - Job 1307: Subtask extract
[2023-08-02 01:02:19,766] {task_command.py:371} INFO - Running <TaskInstance: etl_api_marvel_2.extract manual__2023-08-02T01:02:16.701192+00:00 [running]> on host 24cbf2f01ed0
[2023-08-02 01:02:20,004] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=etl_api_marvel_2
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T01:02:16.701192+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T01:02:16.701192+00:00
[2023-08-02 01:02:21,122] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 01:02:21,151] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_api_marvel_2, task_id=extract, execution_date=20230802T010216, start_date=20230802T010219, end_date=20230802T010221
[2023-08-02 01:02:21,207] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 01:02:21,255] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-08-02 01:02:23,955] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
