[2023-08-01 23:09:17,707] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.extract manual__2023-08-01T23:09:15.162839+00:00 [queued]>
[2023-08-01 23:09:17,727] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_api_marvel_2.extract manual__2023-08-01T23:09:15.162839+00:00 [queued]>
[2023-08-01 23:09:17,727] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:09:17,727] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-08-01 23:09:17,727] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 23:09:17,779] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract> on 2023-08-01 23:09:15.162839+00:00
[2023-08-01 23:09:17,807] {standard_task_runner.py:52} INFO - Started process 1284 to run task
[2023-08-01 23:09:17,821] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_api_marvel_2', 'extract', 'manual__2023-08-01T23:09:15.162839+00:00', '--job-id', '1262', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_multiple_tasks_no_failure.py', '--cfg-path', '/tmp/tmpysr8hdgj', '--error-file', '/tmp/tmphxk9dc2i']
[2023-08-01 23:09:17,823] {standard_task_runner.py:80} INFO - Job 1262: Subtask extract
[2023-08-01 23:09:18,037] {task_command.py:371} INFO - Running <TaskInstance: etl_api_marvel_2.extract manual__2023-08-01T23:09:15.162839+00:00 [running]> on host 24cbf2f01ed0
[2023-08-01 23:09:18,450] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=arielmfeldman.af@gmail.com
AIRFLOW_CTX_DAG_OWNER=Ariel Feldman
AIRFLOW_CTX_DAG_ID=etl_api_marvel_2
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T23:09:15.162839+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T23:09:15.162839+00:00
[2023-08-01 23:09:19,611] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 23:09:19,697] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=etl_api_marvel_2, task_id=extract, execution_date=20230801T230915, start_date=20230801T230917, end_date=20230801T230919
[2023-08-01 23:09:19,821] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 23:09:19,991] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-08-01 23:09:22,763] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
